name: al_quran_v3
description: "A Flutter application for reading the Holy Quran, tracking prayer times, and managing Islamic practices."
publish_to: none

version: 3.14.2+72

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  gap: ^3.0.1
  fluentui_system_icons: ^1.1.273
  intl: ^0.20.2
  html: ^0.15.5
  http: ^1.4.0
  archive: ^4.0.5
  meta: ^1.16.0
  bloc: ^9.0.0
  dio: ^5.8.0+1
  scrollable_positioned_list: ^0.3.8
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  vector_math: ^2.1.4
  geocoding: ^4.0.0
  flutter_svg: ^2.0.17
  vibration: ^3.1.3
  just_audio: ^0.10.3
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: any
  media_kit_libs_windows_audio: any
  just_audio_background: ^0.0.1-beta.17
  audio_video_progress_bar: ^2.0.3
  dartx: ^1.2.0
  fluttertoast: ^9.0.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  clipboard: ^3.0.8
  flutter_html: ^3.0.0
  visibility_detector: ^0.4.0+2
  # alarm:
  #   git:
  #     url: https://github.com/IsmailHosenIsmailJames/alarm.git
  cached_network_image: ^3.4.1
  screenshot: ^3.0.0
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  # flutter_spinkit: ^5.2.1
  simple_icons: ^14.6.1
  uuid: ^4.5.1
  flex_color_picker: ^3.7.1
  window_manager: ^0.5.0
  # awesome_notifications: ^0.10.1
  path: ^1.9.1
  wakelock_plus: ^1.3.2
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.2
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  google_fonts: ^6.3.2
  web: ^1.1.1
  flutter_native_splash: ^2.4.7
  adhan_dart: ^1.2.0
  hijri: ^3.0.0
  shimmer: ^3.0.0
  # background_fetch:
  #   git:
  #     url: https://github.com/transistorsoft/flutter_background_fetch
  # firebase_core: ^4.2.1
  # firebase_ai: ^3.6.0
  # firebase_auth: ^6.1.2
  # firebase_database: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_to_debian: ^2.0.2


  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  icons_launcher: ^3.0.1
  flutter_gen: ^5.10.0
  msix: ^3.16.12

msix_config:
  display_name: "Quran's Tafsir, Audio and Prayer"
  publisher_display_name: "MD. Ismail Hosen"
  identity_name: MD.IsmailHosen.com.ismail.al-quran
  publisher: "CN=B9F6AC9B-F4A4-426C-9C75-82E3872E24AB"
  msix_version: 3.8.0.0
  logo_path: "assets\\img\\Quran_Logo_v3.png"
  capabilities: "internetClient, location"
  store: true


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/img/sunrise_forbidden_time.png
    - assets/
    - assets/dev/
    - assets/quran_script/
    - assets/meta_data/
    - assets/adhan/

  fonts:
    - family: QPC_Hafs
      fonts:
        - asset: assets/fonts/Quran/QPC Hafs font.ttf

    - family: AlQuranNeov5x1
      fonts:
        - asset: assets/fonts/Quran/AlQuranNeov5x1.ttf

    - family: IndopakNastaleeq
      fonts:
        - asset: assets/fonts/Quran/Indopak Nastaleeq font.ttf
    - family: surah-name-v1
      fonts:
        - asset: assets/fonts/Quran/surah-name-v1.ttf


    - family: KFGQPC-Uthmanic-HAFS-Regular
      fonts:
        - asset: assets/fonts/Quran/KFGQPC Uthmanic Script HAFS Regular.otf

    # - family: NotoSans
    #   fonts:
    #     - asset: assets/fonts/App/NotoSans-Bold.ttf
    #       weight: 700
    #     # - asset: assets/fonts/App/NotoSans-ExtraLight.ttf
    #     #   weight: 200
    #     # - asset: assets/fonts/App/NotoSans-Light.ttf
    #     #   weight: 300
    #     - asset: assets/fonts/App/NotoSans-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/App/NotoSans-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/App/NotoSans-SemiBold.ttf
    #       weight: 600

icons_launcher:
  image_path: "assets/img/Quran_Logo_v3.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
      image_path: "assets/img/Quran_Logo_v3.jpg"

    windows:
      enable: false
      image_path: "assets/img/Quran_Logo_v3.png"

    linux:
      enable: true
      image_path: "assets/img/Quran_Logo_v3.png"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/Quran_Logo_v3.png"
  min_sdk_android: 21 

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/Quran_Logo_v3_splah_big.png
  branding: assets/img/Quran_Logo_v3_splah_big.png
  color_dark: "#121212"
  image_dark: assets/img/Quran_Logo_v3_splah_big.png
  branding_dark: assets/img/Quran_Logo_v3_splah_big.png

  android_12:
    image: assets/img/Quran_Logo_v3_splah_big.png
    icon_background_color: "#ffffff"
    image_dark: assets/img/Quran_Logo_v3_splah_big.png
    icon_background_color_dark: "#121212"
